### ISSUE TITLE
building library on macOS 12

### ISSUE THREAD

**Issue by nicarran** [nicarran/jpen#2]
This issue is being reported by @edgar79 : there is a linker error when compiling the osx provider for macOS. The problem is described in detail on [this SF discussion thread](https://sourceforge.net/p/jpen/discussion/753961/thread/4c35c6b6/).

I can't help with the osx provider. This binary and the latest osx provider code was kindly contributed by @marcello3d . This post will probably notify him. Let's see if he is able to give us some feedback.

**Comment by marcello3d** [comment]
Hallo! I gave up on trying to get Java to play nicely with tablets on Mac 4 years ago and haven't done any macOS development since then. :-(

I don't personally have time to work on it, but if someone does, try to find example macOS code from https://developer.wacom.com/ — that's what the current code is based on (they've completely changed the site since last time I worked on this).

**Comment by edgar79** [comment]
- I have fixed the compiler error.

- There are some deprecation warnings since macOS 10.12, but i could compile it (without changing them) to be compatible with min-version 10.7.

- The linker error is (probably) only maven-nar related and i found references how to configure it for mac.

My **question** is:
Should i introduce an alternative binary (and a new source tree src/main/c/macos ) to be selected based on OS version ? (would keep the working binary for older OS than 10.7 )

Or should i update the sources under src/main/c/osx  (just introducing a new binary "nativeVersion") ?

**Comment by edgar79** [comment]
Hello,
I just tested the rotation and there is a bug on macOS (probably in the os x provider), so I would answer the question myself and would try to fix the existing os x source tree. But this could take me a longer time cause I got to learn more about JNI and C.

**Comment by edgar79** [comment]
Hello @marcello3d ,

most important: Thank you for your work :)

The os x provider of JPen 2.0.0 is working fine
but your post sounded a bit like there have been open issues or something like that 
if this was the case, do you still remember any of them ?

Kind regards,
Hannes Schäuble

**Comment by marcello3d** [comment]
I remember compatibility problems between different versions of OS X. And the other big issue was Java Applet integration (which JPen didn't really focus on). See https://github.com/marcello3d/jtablet and http://jtablet.cellosoft.com/develop.html
